trigger:  none
pr:
  branches:
    include:
      - 'main'
  paths:
    include:
      - ./terraform
  
      
pool:
  vmImage: ubuntu-latest


parameters:
  - name: Env
    values:
      - dev
      - prod
      - uat

variables:
- template: ../variables/${{ parameters.Env }}.yml
steps:

  
- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    addSpnToEnvironment: true
    scriptLocation: inlineScript
    workingDirectory: $(Build.SourcesDirectory)/terraform
    inlineScript: |
      export ARM_CLIENT_ID=$servicePrincipalId
      export ARM_CLIENT_SECRET=$servicePrincipalKey
      export ARM_SUBSCRIPTION_ID=`az account show -o json | jq .id | tr -d '"'`
      export ARM_TENANT_ID=$tenantId

      terraform validate
      terraform init
      terraform plan





    


