trigger:  none
pr:
  branches:
    exclude:
      - '*'
pool:
  vmImage: ubuntu-latest

parameters:
  - name: Env
    default: dev
    values:
      - prod
      - dev
      - uat

steps:
- script: echo $ {{ parameters.Env }}


    


